---
title: "mjsalnic_FinalHomeworkCode_01"
author: "Majo Salazar"
date: "9/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r Module 04 Practice}
```


```{r Matrices and Arrays Practice}
library(stringr)
m <- matrix(data=c(1,2,3,4),nrow=2,ncol=2)
m

m <- matrix(data=c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=FALSE)
m

m <- matrix(data=c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=TRUE)

m


##You can also create matrices in R by binding vectors of the same length together either row-wise (with the function rbind()) or column-wise (with the function cbind()).

v1<- c(1,2,3,4)
v2<- c(6,7,8,9)
m1<- rbind(v1,v2)
m1
##always double-check if the script is complete, 1st attempt I forgot to include the m1 at the end
m2 <- cbind(v1,v2)
m2

###Metadata about a matrix can be extracted using the class(), dim(), names(), rownames(), colnames() and other commands. The dim() command returns a vector containing the number of rows at index position 1 and the number of columns at index position 2.

class(m1)
dim(m1)
class(m2)
dim(m2)
colnames(m2)
rownames(m2)
str(m2)
## ARRAY An array is a more general data structure, of which a vector (with 1 implicit dimension) and a matrix (with 2 defined dimensions) are but examples. Arrays can include additional dimensions, but (like vectors and matrices) they can only include elements that are all of the same atomic data class (e.g., numeric, character). The example below shows the construction of a 3 dimensional array with 5 rows, 6 columns, and 3 “levels”). Visualizing higher and higher dimension arrays, obviously, becomes challenging!
a <- array(data=1:90, dim=c(5,6,3))
a

##Subsetting: You can select elements from vectors, matrices, and arrays by subsetting them using their index position(s) in bracket notation. For vectors, you would specify an index value in one dimension. For matrices, you would give the index values in two dimensions. For arrays generally, you would give index values for each dimension in the array.

v <- 1:100
v
v[1:15]
v[c(2,4,6,8,10)]
##You can also use a function or a calculation to subset a vector. What does the following return?
v <- 101:200
v[seq(from = 1, to = 100, by = 2)]
```


```{r Challenge 1}
##
#Homework 1 week 2

##create a vector of 1 word character 

Ulysses = c("Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed")
Ulysses
strsplit(Ulysses, " ")
splitUlysses <- str_split(Ulysses , " ")
vector_Ulysses <-unlist(splitUlysses)
ThirdWord<- vector_Ulysses[seq(from=1, to=22, by=3 )]
ThirdWord

##Matrix example

m <- matrix(data=1:80,nrow=8,ncol=10,byrow=FALSE)
m
x <- m[4,5]
x
m[row=5,]
```

```{r Challenge 2}

##Challenge 2
### First and Third Column with All rows example: variable name<- m[,c(1,3)]

x <- m[,c(2,3,6)]
x
x <- m[6:8,]
x
x <- m[2:6,2:9]
x
## It took me a while to figured out how to put this together- challenge 2.3
```

```{r Challenge 3}

#Challenge 3

##Construct a 4-dimensional, 400 element array (5 x 5 x 4 x 4) named a consisting of the numbers 400 to 1 (i.e., a descending series)
a <- array(data=400:1, dim=c(5,5,4,4))
a
a[1, 1, 1, 2]

a[2, 3, 2, ]

a[1:5, 1:5, 3, 3]
m[7,1] <- 564
m[,8] <- 2
m[2:5,4:8] <- 1
m[2:5,4:8] <- c(20,19,18,17)
m[2:5,4:8] <- matrix(data = c(20:1), nrow=4,ncol=5,byrow=TRUE)
m[,8] <- c("a","b")
```


```{r List and data frames practice}
s <- c("this","is","a","vector","of","strings")
m <- matrix(data=1:40, nrow=5, ncol=8) # this is a matrix
b <- FALSE
l <- list(s, m, b)
l
l[[2]]
##You can extract elements from a list similarly to how you would from other data structure, except that you use double brackets to reference a single element in the list
l[[2]][2,6]
l[1:2]
l[c(1,3)]
str(l)
names(l) <- c("string", "matrix", "logical")
names(l)
l$string
l$matrix[3,5]
```


```{r Challenge 4}

Platyrrhini<-c("Cebidae","Atelidae","Pitheciidae")

Catarrhini<-c("Cercopithecidae","Hylobatidae","Hominidae")

Anthropoidea<-list(Platyrrhini,Catarrhini)

names(Anthropoidea)<-c("Platyrrhini","Catarrhini")

Tarsioidea<-c("Tarsiidae")

Haplorhini<-list(Anthropoidea,Tarsioidea)

names(Haplorhini)<-c("Anthropoidea","Tarsioidea")

Lorisoidea<-c("Lorisidae","Galagidae")

Lemuroidea<-c("Cheirogaleidae","Lepilemuridae","Indriidae","Lemuridae","Daubentoniidae")
Strepsirhini<-list(Lorisoidea,Lemuroidea)

names(Strepsirhini)<-c("Lorisoidea","Lemuroidea")

Primates<-list(Haplorhini,Strepsirhini)

names(Primates)<-c("Haplorhini","Strepsirhini")

Primates
```

```{r Data frame practice}

df <- data.frame(firstName=c("Nitin","Silvy","Ingrid","Claire"), program=c("iSchool","Anthro","Anthro","EEB"), sex=c("M","F","F","F"), yearInProgram=c(1,2,2,3))
df
###Data frame
df <- read.csv("C:/Users/majo_/Desktop/random-people.csv", stringsAsFactors=FALSE)
View(df)
df[,c(1,3,4,11,12)]
str(df)
df[,3]
str(df[,3])
df$name.last
str(df$name.last)
df[3]
str(df[3])
df["name.last"]
str(df["name.last"])
df <- cbind(df, id=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))
df <- cbind(df, school=c("BU","BU","Harvard","Harvard","BU","Boston College","MIT","BU","BU","UMASS Boston","Harvard","BU","Boston College","BU","Harvard","MIT","Harvard","BU", "UMASS Boston", "Harvard"))
df

df$school <- c("BU","BU","Harvard","Harvard","BU","Boston College","MIT","BU","BU","UMASS Boston","Harvard","BU","Boston College","BU","Harvard","MIT","Harvard","BU", "UMASS Boston", "Harvard")


new_df <- df[df$school == "BU",]
new_df

new_df <- df[df$school == "BU", c("name.last", "name.first", "school")]
new_df
```

```{r Challenge 5}
##Store the following numbers as a 5 x 3 matrix: 3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2. Be sure to fill the matrix ROWWISE
m <- matrix(data=c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2),nrow=5,ncol=3,byrow=TRUE)
m
dfm<-data.frame(m)
dfm

as.logical(dfm[,2])
as.factor(dfm[,3])
str(dfm)
```

```{r Majo challenges}

##1. Challenge 1: I think there would be more than one way to extract elements from a character vector. I found the "word "function could fo that but I couldn't be able to do it for this challenge, this is an example of how to use this function, it would be useful if works for extract nth element from a character vector.
# some sentence
# change = c("Be the change", "you want to be")
# extract first word
# word(change, 1)
# [1] "Be" "you"

##2.Challenge 2: It took me a while to figured out how to put this together- challenge 2.3 
##3. I had trouble with the csv file, I had to open in excel and save it as csv file to then opened using "Import dataset" from environment window and setting heading and not strings as factor from there.
##4. List and data frame part of the module isn't completely clear for me

##5. Challenge 4: I spent a lot of time searching how to do the Primates list, I got very confused, I wasn't able to create subheadings, I could only create a list for each subheading containing the elements for that subheading, but when ran the script everything was in the same level, not separate by subheadings
 

```


```{r Peer Commentary}
#I think that the single vector form that you used was a cleaner look for the final output in Challenge 4. Mine had so many dimensions that were shown for each entry. 

#Im not sure how much help my code is. Most of it is the same as yours. My main differences were the Taxonomy(below), and I had an extra step unn my Ulysses code that I can take out

#We both had problems with visulizing data for the taxonomy. For my code, I made nested lists of taxonomy as a list, which was sort of opposite of yours.

Platyrrhini<- list("Cebidae", "Atelidae", "Pitheciidae")
Catarrhini<- list("Cercopithecidae", "Hylobatidae", "Hominidae")
Anthropoidea<-list(Platyrrhini, Catarrhini)

Tarsioidea<-list("Tarsiidae")

Haplorhini<- list(Anthropoidea, Tarsioidea)

Lorisoidea<- list("Lorisidae", "Galagidae")
Lemuroidea<- list("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae")

Strepsirhini<- list(Lorisoidea, Lemuroidea)

Primates<- list(Haplorhini, Strepsirhini)
Primates

#I found it a bit confusing that you started with the largest category first. My instinct would have been to assume you had to start small and build up. However, your code worked well, so it is good to know you can work in either direction in R.

#When I knitted this to look at it, it was a bit confusing. I think with RMarkdown files, adding chunks makes it look a bit better, though it doesn't change the actual code. I think the actual annotations were fine though. 

```



